package com.cout970.magneticraft;

import java.util.LinkedList;
import java.util.List;

import com.cout970.magneticraft.block.BlockAirBubble;
import com.cout970.magneticraft.block.BlockAirlock;
import com.cout970.magneticraft.block.BlockBasicGenerator;
import com.cout970.magneticraft.block.BlockBattery;
import com.cout970.magneticraft.block.BlockBiomassBurner;
import com.cout970.magneticraft.block.BlockBoiler;
import com.cout970.magneticraft.block.BlockBreaker;
import com.cout970.magneticraft.block.BlockBrickFurnace;
import com.cout970.magneticraft.block.BlockCombustionEngine;
import com.cout970.magneticraft.block.BlockComputer;
import com.cout970.magneticraft.block.BlockConcretedPipe;
import com.cout970.magneticraft.block.BlockConveyorLow;
import com.cout970.magneticraft.block.BlockCooler;
import com.cout970.magneticraft.block.BlockCopperTank;
import com.cout970.magneticraft.block.BlockCrafter;
import com.cout970.magneticraft.block.BlockCrusher;
import com.cout970.magneticraft.block.BlockDiode;
import com.cout970.magneticraft.block.BlockDroidRED;
import com.cout970.magneticraft.block.BlockEUAlternator;
import com.cout970.magneticraft.block.BlockElectricFurnace;
import com.cout970.magneticraft.block.BlockElectricPoleCableWire;
import com.cout970.magneticraft.block.BlockElectricPoleTier1;
import com.cout970.magneticraft.block.BlockElectricSwitch;
import com.cout970.magneticraft.block.BlockFireBox;
import com.cout970.magneticraft.block.BlockFluidHopper;
import com.cout970.magneticraft.block.BlockGeothermalPump;
import com.cout970.magneticraft.block.BlockGrinder;
import com.cout970.magneticraft.block.BlockGrindingMill;
import com.cout970.magneticraft.block.BlockGrindingMillGap;
import com.cout970.magneticraft.block.BlockHammerTable;
import com.cout970.magneticraft.block.BlockHandCrankGenerator;
import com.cout970.magneticraft.block.BlockHeatResistence;
import com.cout970.magneticraft.block.BlockHeatSink;
import com.cout970.magneticraft.block.BlockHeater;
import com.cout970.magneticraft.block.BlockInfiniteEnergy;
import com.cout970.magneticraft.block.BlockInfiniteSteam;
import com.cout970.magneticraft.block.BlockInfiniteWater;
import com.cout970.magneticraft.block.BlockInserter;
import com.cout970.magneticraft.block.BlockKineticGenerator;
import com.cout970.magneticraft.block.BlockMB_Chassis;
import com.cout970.magneticraft.block.BlockMB_Controls;
import com.cout970.magneticraft.block.BlockMB_Energy_Low;
import com.cout970.magneticraft.block.BlockMB_Energy_Medium;
import com.cout970.magneticraft.block.BlockMB_Heat;
import com.cout970.magneticraft.block.BlockMB_Inv;
import com.cout970.magneticraft.block.BlockMB_Kinetic;
import com.cout970.magneticraft.block.BlockMachineHousing;
import com.cout970.magneticraft.block.BlockMiner;
import com.cout970.magneticraft.block.BlockMirror;
import com.cout970.magneticraft.block.BlockMonitor;
import com.cout970.magneticraft.block.BlockOfIngots;
import com.cout970.magneticraft.block.BlockOilDistillery;
import com.cout970.magneticraft.block.BlockOilSource;
import com.cout970.magneticraft.block.BlockOilSourceDrained;
import com.cout970.magneticraft.block.BlockOre;
import com.cout970.magneticraft.block.BlockPermanentMagnet;
import com.cout970.magneticraft.block.BlockPolymerizer;
import com.cout970.magneticraft.block.BlockPressureTank;
import com.cout970.magneticraft.block.BlockPumpJack;
import com.cout970.magneticraft.block.BlockRCAlternator;
import com.cout970.magneticraft.block.BlockRFAlternator;
import com.cout970.magneticraft.block.BlockReactorActivator;
import com.cout970.magneticraft.block.BlockReactorControlRods;
import com.cout970.magneticraft.block.BlockReactorController;
import com.cout970.magneticraft.block.BlockReactorVessel;
import com.cout970.magneticraft.block.BlockReactorWall;
import com.cout970.magneticraft.block.BlockRefinery;
import com.cout970.magneticraft.block.BlockRefineryGap;
import com.cout970.magneticraft.block.BlockRefineryTank;
import com.cout970.magneticraft.block.BlockResistance;
import com.cout970.magneticraft.block.BlockSifter;
import com.cout970.magneticraft.block.BlockSolarPanel;
import com.cout970.magneticraft.block.BlockSolarTowerCore;
import com.cout970.magneticraft.block.BlockSteamEngine;
import com.cout970.magneticraft.block.BlockSteamTurbine;
import com.cout970.magneticraft.block.BlockStirlingGenerator;
import com.cout970.magneticraft.block.BlockTeslaCoil;
import com.cout970.magneticraft.block.BlockThermopile;
import com.cout970.magneticraft.block.BlockTransformerLow_Medium;
import com.cout970.magneticraft.block.BlockTransformerMedium_High;
import com.cout970.magneticraft.block.BlockVoidInventory;
import com.cout970.magneticraft.block.BlockWindTurbine;
import com.cout970.magneticraft.block.BlockWoodenShaft;
import com.cout970.magneticraft.items.ItemBlockMg;
import com.cout970.magneticraft.tileentity.TileAirlock;
import com.cout970.magneticraft.tileentity.TileBase;
import com.cout970.magneticraft.tileentity.TileBasicGenerator;
import com.cout970.magneticraft.tileentity.TileBattery;
import com.cout970.magneticraft.tileentity.TileBiomassBurner;
import com.cout970.magneticraft.tileentity.TileBoiler;
import com.cout970.magneticraft.tileentity.TileBreaker;
import com.cout970.magneticraft.tileentity.TileBrickFurnace;
import com.cout970.magneticraft.tileentity.TileCombustionEngine;
import com.cout970.magneticraft.tileentity.TileComputer;
import com.cout970.magneticraft.tileentity.TileConveyorBelt;
import com.cout970.magneticraft.tileentity.TileCooler;
import com.cout970.magneticraft.tileentity.TileCopperTank;
import com.cout970.magneticraft.tileentity.TileCrafter;
import com.cout970.magneticraft.tileentity.TileCrusher;
import com.cout970.magneticraft.tileentity.TileDiode;
import com.cout970.magneticraft.tileentity.TileDroidRED;
import com.cout970.magneticraft.tileentity.TileEUAlternator;
import com.cout970.magneticraft.tileentity.TileElectricFurnace;
import com.cout970.magneticraft.tileentity.TileElectricPoleCableWire;
import com.cout970.magneticraft.tileentity.TileElectricPoleCableWireDown;
import com.cout970.magneticraft.tileentity.TileElectricPoleGap;
import com.cout970.magneticraft.tileentity.TileElectricPoleTier1;
import com.cout970.magneticraft.tileentity.TileElectricSwitch;
import com.cout970.magneticraft.tileentity.TileFireBox;
import com.cout970.magneticraft.tileentity.TileFluidHopper;
import com.cout970.magneticraft.tileentity.TileGeothermalPump;
import com.cout970.magneticraft.tileentity.TileGrinder;
import com.cout970.magneticraft.tileentity.TileGrindingMill;
import com.cout970.magneticraft.tileentity.TileHammerTable;
import com.cout970.magneticraft.tileentity.TileHandCrankGenerator;
import com.cout970.magneticraft.tileentity.TileHeatResistance;
import com.cout970.magneticraft.tileentity.TileHeatSink;
import com.cout970.magneticraft.tileentity.TileHeater;
import com.cout970.magneticraft.tileentity.TileInfiniteEnergy;
import com.cout970.magneticraft.tileentity.TileInfiniteSteam;
import com.cout970.magneticraft.tileentity.TileInfiniteWater;
import com.cout970.magneticraft.tileentity.TileInserter;
import com.cout970.magneticraft.tileentity.TileKineticGenerator;
import com.cout970.magneticraft.tileentity.TileMB_Base;
import com.cout970.magneticraft.tileentity.TileMB_Controls;
import com.cout970.magneticraft.tileentity.TileMB_Energy_Low;
import com.cout970.magneticraft.tileentity.TileMB_Energy_Medium;
import com.cout970.magneticraft.tileentity.TileMB_Heat;
import com.cout970.magneticraft.tileentity.TileMB_Inv;
import com.cout970.magneticraft.tileentity.TileMB_Kinetic;
import com.cout970.magneticraft.tileentity.TileMB_Remplaced;
import com.cout970.magneticraft.tileentity.TileMiner;
import com.cout970.magneticraft.tileentity.TileMirror;
import com.cout970.magneticraft.tileentity.TileOilDistillery;
import com.cout970.magneticraft.tileentity.TilePermanentMagnet;
import com.cout970.magneticraft.tileentity.TilePolymerizer;
import com.cout970.magneticraft.tileentity.TilePressureTank;
import com.cout970.magneticraft.tileentity.TilePumpJack;
import com.cout970.magneticraft.tileentity.TileRCAlternator;
import com.cout970.magneticraft.tileentity.TileRFAlternator;
import com.cout970.magneticraft.tileentity.TileReactorActivator;
import com.cout970.magneticraft.tileentity.TileReactorControlRods;
import com.cout970.magneticraft.tileentity.TileReactorController;
import com.cout970.magneticraft.tileentity.TileReactorVessel;
import com.cout970.magneticraft.tileentity.TileReactorWall;
import com.cout970.magneticraft.tileentity.TileRefinery;
import com.cout970.magneticraft.tileentity.TileRefineryTank;
import com.cout970.magneticraft.tileentity.TileResistance;
import com.cout970.magneticraft.tileentity.TileSifter;
import com.cout970.magneticraft.tileentity.TileSolarPanel;
import com.cout970.magneticraft.tileentity.TileSolarTowerCore;
import com.cout970.magneticraft.tileentity.TileSteamEngine;
import com.cout970.magneticraft.tileentity.TileSteamTurbineControl;
import com.cout970.magneticraft.tileentity.TileStirlingGenerator;
import com.cout970.magneticraft.tileentity.TileTeslaCoil;
import com.cout970.magneticraft.tileentity.TileTextMonitor;
import com.cout970.magneticraft.tileentity.TileThermopile;
import com.cout970.magneticraft.tileentity.TileTransformerLow_Medium;
import com.cout970.magneticraft.tileentity.TileTransformerMedium_High;
import com.cout970.magneticraft.tileentity.TileVoidInventory;
import com.cout970.magneticraft.tileentity.TileWindTurbine;
import com.cout970.magneticraft.tileentity.TileWindTurbineGap;
import com.cout970.magneticraft.tileentity.TileWoodenShaft;
import com.cout970.magneticraft.util.NamedBlock;
import com.cout970.magneticraft.util.tile.TileConductorLow;
import com.cout970.magneticraft.util.tile.TileHeatConductor;

import cpw.mods.fml.common.registry.GameRegistry;
import net.minecraft.block.Block;
import net.minecraft.tileentity.TileEntity;

public class ManagerBlocks {

	public static List<Class<? extends TileEntity>> tileEntities = new LinkedList<Class<? extends TileEntity>>();
	public static List<Block> blocks = new LinkedList<Block>();
	public static List<NamedBlock> named = new LinkedList<NamedBlock>();

	public static Block oreCopper;
	public static Block oreTungsten;
	public static Block oreUranium;
	public static Block oreSulfur;
	public static Block oreThorium;
	public static Block oreZinc;
	public static Block oreSalt;
	public static Block oilSource;
	public static Block oilSourceDrained;
	public static Block ingot_block_copper;
	public static Block ingot_block_tungsten;
	public static Block ingot_block_carbide;
	public static Block ingot_block_brass;
	public static Block ingot_block_zinc;
	public static Block dust_block_salt;
	public static Block dust_block_sulfur;
	public static Block solarpanel;
	public static Block furnace;
	public static Block battery;
	public static Block transformer_lm;
	public static Block transformer_mh;
	public static Block firebox;
	public static Block boiler;
	public static Block cooler;
	public static Block heat_resist;
	public static Block fluidhopper;
	public static Block basic_gen;
	public static Block pumpJack;
	public static Block steam_engine;
	public static Block crusher;
	public static Block chassis;
	public static Block multi_io;
	public static Block conveyor_l;
	public static Block mirror;
	public static Block breaker;
	public static Block kinetic;
	public static Block windturbine;
	public static Block geothermal;
	public static Block permagnet;
	public static Block concreted_pipe;
	public static Block reactor_vessel;
	public static Block thermopile;
	public static Block multi_energy_low;
	public static Block reactor_control_rods;
	public static Block reactor_wall;
	public static Block reactor_activator;
	public static Block inserter;
	public static Block housing;
	public static Block grinder;
	public static Block miner;
	public static Block tesla_coil;
	public static Block airlock;
	public static Block biomass_burner;
	public static Block stirling;
	public static Block infinite_water;
	public static Block refinery;
	public static Block refinery_gap;
	public static Block refinery_tank;
	public static Block copper_tank;
	public static Block heater;
	public static Block air_bubble;
	public static Block solar_tower_core;
	public static Block polimerizer;
	public static Block reactor_controller;
	public static Block multi_energy_medium;
	public static Block steam_turbine;
	public static Block combustion_engine;
	public static Block heat_sink;
	public static Block brickFurnace;
	public static Block crafter;
	public static Block monitor;
	public static Block cpu;
	public static Block multi_heat;
	public static Block pole_tier1;
	public static Block droid_red;
	public static Block oil_distillery;
	public static Block grinding_mill;
	public static Block multi_kinetic;
	public static Block grinding_mill_gap;
	public static Block wooden_shaft;
	public static Block hand_crank_gen;
	public static Block infinite_steam;
	public static Block void_inv;
	public static Block electric_switch;
	public static Block diode;
	public static Block resistance;
	public static Block rf_alternator;
	public static Block rc_alternator;
	public static Block eu_alternator;
	public static Block pole_cable_wire;
	public static Block infinite_energy;
	public static Block sifter;
	public static Block mb_controls;
	public static Block pressure_tank;
	public static Block hammer_table;

	public static void initBlocks() {
		// ores & resources
		oilSource = new BlockOilSource();
		oreCopper = new BlockOre("copper_ore");
		oreTungsten = new BlockOre("tungsten_ore");
		oreUranium = new BlockOre("uranium_ore");
		oreSulfur = new BlockOre("sulfur_ore");
		oreThorium = new BlockOre("thorium_ore");
		oreSalt = new BlockOre("salt_ore");
		oilSourceDrained = new BlockOilSourceDrained();
		solarpanel = new BlockSolarPanel();
		furnace = new BlockElectricFurnace();
		battery = new BlockBattery();
		transformer_lm = new BlockTransformerLow_Medium();
		transformer_mh = new BlockTransformerMedium_High();
		kinetic = new BlockKineticGenerator();
		basic_gen = new BlockBasicGenerator();
		firebox = new BlockFireBox();
		boiler = new BlockBoiler();
		conveyor_l = new BlockConveyorLow();
		pumpJack = new BlockPumpJack();
		cooler = new BlockCooler();
		crusher = new BlockCrusher();
		chassis = new BlockMB_Chassis();
		multi_io = new BlockMB_Inv();
		mirror = new BlockMirror();
		windturbine = new BlockWindTurbine();
		permagnet = new BlockPermanentMagnet();
		fluidhopper = new BlockFluidHopper();
		heat_resist = new BlockHeatResistence();
		breaker = new BlockBreaker();
		steam_engine = new BlockSteamEngine();
		geothermal = new BlockGeothermalPump();
		concreted_pipe = new BlockConcretedPipe();
		reactor_vessel = new BlockReactorVessel();
		thermopile = new BlockThermopile();
		multi_energy_low = new BlockMB_Energy_Low();
		reactor_control_rods = new BlockReactorControlRods();
		reactor_wall = new BlockReactorWall();
		inserter = new BlockInserter();
		reactor_activator = new BlockReactorActivator();
		housing = new BlockMachineHousing();
		grinder = new BlockGrinder();
		miner = new BlockMiner();
		tesla_coil = new BlockTeslaCoil();
		airlock = new BlockAirlock();
		biomass_burner = new BlockBiomassBurner();
		stirling = new BlockStirlingGenerator();
		infinite_water = new BlockInfiniteWater();
		refinery = new BlockRefinery();
		refinery_gap = new BlockRefineryGap();
		refinery_tank = new BlockRefineryTank();
		copper_tank = new BlockCopperTank();
		heater = new BlockHeater();
		air_bubble = new BlockAirBubble();
		solar_tower_core = new BlockSolarTowerCore();
		polimerizer = new BlockPolymerizer();
		reactor_controller = new BlockReactorController();
		multi_energy_medium = new BlockMB_Energy_Medium();
		steam_turbine = new BlockSteamTurbine();
		combustion_engine = new BlockCombustionEngine();
		heat_sink = new BlockHeatSink();
		brickFurnace = new BlockBrickFurnace();
		crafter = new BlockCrafter();
		monitor = new BlockMonitor();
		cpu = new BlockComputer();
		multi_heat = new BlockMB_Heat();
		pole_tier1 = new BlockElectricPoleTier1();
		droid_red = new BlockDroidRED();
		oil_distillery = new BlockOilDistillery();
		grinding_mill = new BlockGrindingMill();
		grinding_mill_gap = new BlockGrindingMillGap();
		wooden_shaft = new BlockWoodenShaft();
		hand_crank_gen = new BlockHandCrankGenerator();
		multi_kinetic = new BlockMB_Kinetic();
		infinite_steam = new BlockInfiniteSteam();
		void_inv = new BlockVoidInventory();
		electric_switch = new BlockElectricSwitch();
		diode = new BlockDiode();
		resistance = new BlockResistance();
		rf_alternator = new BlockRFAlternator();
		rc_alternator = new BlockRCAlternator();
		eu_alternator = new BlockEUAlternator();
		pole_cable_wire = new BlockElectricPoleCableWire();
		infinite_energy = new BlockInfiniteEnergy();
		sifter = new BlockSifter();
		ingot_block_copper = new BlockOfIngots("block_copper");
		ingot_block_tungsten = new BlockOfIngots("block_tungsten");
		ingot_block_carbide = new BlockOfIngots("block_carbide");
		ingot_block_brass = new BlockOfIngots("block_brass");
		ingot_block_zinc = new BlockOfIngots("block_zinc");
		dust_block_salt = new BlockOfIngots("block_salt");
		dust_block_sulfur = new BlockOfIngots("block_sulfur");
		mb_controls = new BlockMB_Controls();
		oreZinc = new BlockOre("zinc_ore");
		pressure_tank = new BlockPressureTank();
		hammer_table = new BlockHammerTable();
	}

	public static void registerBlocks() {

		addBlock(oilSource, "Oil Source");
		addBlock(oilSourceDrained, "Oil Source Drained");
		addBlock(oreCopper, "Copper Ore");
		addBlock(oreSalt, "Salt Ore");
		addBlock(oreSulfur, "Sulfur Ore");
		addBlock(oreThorium, "Thorium Ore");
		addBlock(oreTungsten, "Tungsten Ore");
		addBlock(oreUranium, "Uranium Ore");
		addBlock(ingot_block_copper, "Copper Block");
		addBlock(ingot_block_tungsten, "Tungsten Block");
		addBlock(ingot_block_carbide, "Carbide Block");
		addBlock(ingot_block_brass, "Brass Block");
		addBlock(ingot_block_zinc, "Zinc Block");
		addBlock(solarpanel, "Solar Panel");
		addBlock(furnace, "Electric Furnace");
		addBlock(battery, "Battery");
		addBlock(transformer_lm, "Transformer Low to Medium");
		addBlock(transformer_mh, "Transformer Medium to High");
		addBlock(firebox, "Firebox");
		addBlock(boiler, "Boiler");
		addBlock(cooler, "Cooler");
		addBlock(heat_resist, "Heat Resistance");
		addBlock(fluidhopper, "Fluid Hopper");
		addBlock(basic_gen, "Basic Generator");
		addBlock(pumpJack, "Pumpjack");
		addBlock(steam_engine, "Steam Engine");
		addBlock(crusher, "Crusher Control");
		addBlock(chassis, "Multiblock Chassis");
		addBlock(multi_io, "Multiblock IO");
		addBlock(conveyor_l, "Conveyor Belt");
		addBlock(mirror, "Mirror");
		addBlock(breaker, "Block Breaker");
		addBlock(kinetic, "Kinetic Generator");
		addBlock(windturbine, "Wind Turbine");
		addBlock(geothermal, "Geothermal Pump");
		addBlock(permagnet, "Permanent Magnet");
		addBlock(concreted_pipe, "Concrete");
		addBlock(reactor_vessel, "Reactor Vessel");
		addBlock(thermopile, "Thermopile");
		addBlock(multi_energy_low, "Multiblock Energy IO Low Voltage");
		addBlock(reactor_control_rods, "Reactor Control");
		addBlock(reactor_wall, "Reactor Wall");
		addBlock(reactor_activator, "Reactor Accelerator");
		addBlock(inserter, "Inserter");
		addBlock(housing, "Machine Housing");
		addBlock(grinder, "Grinder Control");
		addBlock(miner, "Miner");
		addBlock(tesla_coil, "Tesla Coil");
		addBlock(airlock, "Airlock");
		addBlock(biomass_burner, "Biomass Burner");
		addBlock(stirling, "Stirling Generator Control");
		addBlock(infinite_water, "Infinite Water");
		addBlock(refinery, "Refinery Control");
		addBlock(refinery_gap, "Multiblock Component");
		addBlock(refinery_tank, "Refinery Tank");
		addBlock(copper_tank, "Fluid Tank");
		addBlock(heater, "Heater");
		addBlock(air_bubble, "Air Bubble");
		addBlock(solar_tower_core, "Solar Tower Core");
		addBlock(polimerizer, "Polymerizer Control");
		addBlock(reactor_controller, "Reactor Controller");
		addBlock(multi_energy_medium, "Multiblock Energy IO Medium Voltage");
		addBlock(steam_turbine, "Turbine Control");
		addBlock(combustion_engine, "Combustion Engine");
		addBlock(heat_sink, "Heat Sink");
		addBlock(brickFurnace, "Brick Furnace");
		addBlock(crafter, "Crafter");
		addBlock(monitor, "Text Monitor");
		addBlock(cpu, "CPU");
		addBlock(multi_heat, "Multiblock Heat IO");
		addBlock(droid_red, "R.E.D.");
		addBlock(oil_distillery, "Oil Distillery Control");
		addBlock(pole_tier1, "Electrical Wooden Pole");
		addBlock(grinding_mill, "Grinding Mill");
		addBlock(grinding_mill_gap, "Grinding Mill");
		addBlock(wooden_shaft, "Wooden Shaft");
		addBlock(hand_crank_gen, "Hand Crank");
		addBlock(multi_kinetic, "Multiblock Kinetic IO");
		addBlock(infinite_steam, "Creative Infinite Steam");
		addBlock(void_inv, "Void Inventory");
		addBlock(electric_switch, "Electric Switch");
		addBlock(diode, "Diode");
		addBlock(resistance, "Resistance");
		addBlock(rf_alternator, "RF Alternator");
		addBlock(rc_alternator, "Railcraft Charge Alternator");
		addBlock(eu_alternator, "EU Alternator");
		addBlock(pole_cable_wire, "Electrical Pole With Transformer");
		addBlock(infinite_energy, "Creative Infinite Energy");
		addBlock(sifter, "Sifter Control");
		addBlock(mb_controls, "Multiblock Controls");
		addBlock(dust_block_salt, "Salt Block");
		addBlock(dust_block_sulfur, "Sulfur Block");
		addBlock(oreZinc, "Zinc Ore");
		addBlock(pressure_tank, "Pressure Tank");
		addBlock(hammer_table, "Hammer Table");

		for (Block b : blocks)
			GameRegistry.registerBlock(b, ItemBlockMg.class, b.getUnlocalizedName());
	}

	public static void registerTileEntities() {

		tileEntities.add(TileBase.class);
		tileEntities.add(TileConductorLow.class);
		tileEntities.add(TileSolarPanel.class);
		tileEntities.add(TileElectricFurnace.class);
		tileEntities.add(TileBattery.class);
		tileEntities.add(TileTransformerLow_Medium.class);
		tileEntities.add(TileTransformerMedium_High.class);
		tileEntities.add(TileKineticGenerator.class);
		tileEntities.add(TileBasicGenerator.class);
		tileEntities.add(TileHeatConductor.class);
		tileEntities.add(TileFireBox.class);
		tileEntities.add(TileBoiler.class);
		tileEntities.add(TileCrusher.class);
		tileEntities.add(TileMB_Inv.class);
		tileEntities.add(TilePumpJack.class);
		tileEntities.add(TileCooler.class);
		tileEntities.add(TileMirror.class);
		tileEntities.add(TileWindTurbine.class);
		tileEntities.add(TilePermanentMagnet.class);
		tileEntities.add(TileFluidHopper.class);
		tileEntities.add(TileHeatResistance.class);
		tileEntities.add(TileBreaker.class);
		tileEntities.add(TileSteamEngine.class);
		tileEntities.add(TileGeothermalPump.class);
		tileEntities.add(TileMB_Base.class);
		tileEntities.add(TileConveyorBelt.class);
		tileEntities.add(TileReactorVessel.class);
		tileEntities.add(TileThermopile.class);
		tileEntities.add(TileMB_Energy_Low.class);
		tileEntities.add(TileReactorControlRods.class);
		tileEntities.add(TileReactorWall.class);
		tileEntities.add(TileInserter.class);
		tileEntities.add(TileReactorActivator.class);
		tileEntities.add(TileGrinder.class);
		tileEntities.add(TileMiner.class);
		tileEntities.add(TileWindTurbineGap.class);
		tileEntities.add(TileTeslaCoil.class);
		tileEntities.add(TileAirlock.class);
		tileEntities.add(TileBiomassBurner.class);
		tileEntities.add(TileStirlingGenerator.class);
		tileEntities.add(TileInfiniteWater.class);
		tileEntities.add(TileRefinery.class);
		tileEntities.add(TileRefineryTank.class);
		tileEntities.add(TileCopperTank.class);
		tileEntities.add(TileHeater.class);
		tileEntities.add(TileSolarTowerCore.class);
		tileEntities.add(TilePolymerizer.class);
		tileEntities.add(TileReactorController.class);
		tileEntities.add(TileSteamTurbineControl.class);
		tileEntities.add(TileMB_Energy_Medium.class);
		tileEntities.add(TileCombustionEngine.class);
		tileEntities.add(TileHeatSink.class);
		tileEntities.add(TileBrickFurnace.class);
		tileEntities.add(TileCrafter.class);
		tileEntities.add(TileTextMonitor.class);
		tileEntities.add(TileComputer.class);
		tileEntities.add(TileMB_Heat.class);
		tileEntities.add(TileElectricPoleTier1.class);
		tileEntities.add(TileDroidRED.class);
		tileEntities.add(TileOilDistillery.class);
		tileEntities.add(TileGrindingMill.class);
		tileEntities.add(TileMB_Remplaced.class);
		tileEntities.add(TileWoodenShaft.class);
		tileEntities.add(TileHandCrankGenerator.class);
		tileEntities.add(TileMB_Kinetic.class);
		tileEntities.add(TileInfiniteSteam.class);
		tileEntities.add(TileVoidInventory.class);
		tileEntities.add(TileElectricSwitch.class);
		tileEntities.add(TileDiode.class);
		tileEntities.add(TileResistance.class);
		tileEntities.add(TileRFAlternator.class);
		tileEntities.add(TileRCAlternator.class);
		tileEntities.add(TileEUAlternator.class);
		tileEntities.add(TileElectricPoleCableWire.class);
		tileEntities.add(TileElectricPoleCableWireDown.class);
		tileEntities.add(TileInfiniteEnergy.class);
		tileEntities.add(TileSifter.class);
		tileEntities.add(TileElectricPoleGap.class);
		tileEntities.add(TileMB_Controls.class);
		tileEntities.add(TilePressureTank.class);
		tileEntities.add(TileHammerTable.class);

		for (Class<? extends TileEntity> c : tileEntities) {
			GameRegistry.registerTileEntity(c, c.getName() + "_Mg");
		}
	}

	private static void addBlock(Block b, String name) {
		blocks.add(b);
		named.add(new NamedBlock(b, name));
	}
}
