// Date: 16/12/2014 15:57:13
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX


package com.cout970.magneticraft.client.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelReactorVessel extends ModelBase {
    //fields
    ModelRenderer pilar1;
    ModelRenderer pilar2;
    ModelRenderer pilar3;
    ModelRenderer pilar4;
    ModelRenderer fuel1;
    ModelRenderer fuel2;
    ModelRenderer fuel3;
    ModelRenderer fuel4;
    ModelRenderer s5;
    ModelRenderer s6;
    ModelRenderer s7;
    ModelRenderer s8;
    ModelRenderer centralrod;

    public ModelReactorVessel() {
        textureWidth = 80;
        textureHeight = 32;

        pilar1 = new ModelRenderer(this, 12, 0);
        pilar1.addBox(5F, 0F, -8F, 3, 16, 3);
        pilar1.setRotationPoint(0F, 8F, 0F);
        pilar1.setTextureSize(80, 32);
        pilar1.mirror = true;
        setRotation(pilar1, 0F, 0F, 0F);
        pilar2 = new ModelRenderer(this, 12, 0);
        pilar2.addBox(5F, 0F, 5F, 3, 16, 3);
        pilar2.setRotationPoint(0F, 8F, 0F);
        pilar2.setTextureSize(80, 32);
        pilar2.mirror = true;
        setRotation(pilar2, 0F, 0F, 0F);
        pilar3 = new ModelRenderer(this, 12, 0);
        pilar3.addBox(-8F, 0F, 5F, 3, 16, 3);
        pilar3.setRotationPoint(0F, 8F, 0F);
        pilar3.setTextureSize(80, 32);
        pilar3.mirror = true;
        setRotation(pilar3, 0F, 0F, 0F);
        pilar4 = new ModelRenderer(this, 12, 0);
        pilar4.addBox(-8F, 0F, -8F, 3, 16, 3);
        pilar4.setRotationPoint(0F, 8F, 0F);
        pilar4.setTextureSize(80, 32);
        pilar4.mirror = true;
        setRotation(pilar4, 0F, 0F, 0F);
        fuel1 = new ModelRenderer(this, 0, 0);
        fuel1.addBox(1F, 1F, 1F, 3, 14, 3);
        fuel1.setRotationPoint(0F, 8F, 0F);
        fuel1.setTextureSize(80, 32);
        fuel1.mirror = true;
        setRotation(fuel1, 0F, 0F, 0F);
        fuel2 = new ModelRenderer(this, 0, 0);
        fuel2.addBox(1F, 1F, -4F, 3, 14, 3);
        fuel2.setRotationPoint(0F, 8F, 0F);
        fuel2.setTextureSize(80, 32);
        fuel2.mirror = true;
        setRotation(fuel2, 0F, 0F, 0F);
        fuel3 = new ModelRenderer(this, 0, 0);
        fuel3.addBox(-4F, 1F, -4F, 3, 14, 3);
        fuel3.setRotationPoint(0F, 8F, 0F);
        fuel3.setTextureSize(80, 32);
        fuel3.mirror = true;
        setRotation(fuel3, 0F, 0F, 0F);
        fuel4 = new ModelRenderer(this, 0, 0);
        fuel4.addBox(-4F, 1F, 1F, 3, 14, 3);
        fuel4.setRotationPoint(0F, 8F, 0F);
        fuel4.setTextureSize(80, 32);
        fuel4.mirror = true;
        setRotation(fuel4, 0F, 0F, 0F);
        s5 = new ModelRenderer(this, 36, 0);
        s5.addBox(-8F, -8F, -5F, 1, 16, 10);
        s5.setRotationPoint(0F, 16F, 0F);
        s5.setTextureSize(80, 32);
        s5.mirror = true;
        setRotation(s5, 0F, 0F, 0F);
        s6 = new ModelRenderer(this, 36, 0);
        s6.addBox(7F, -8F, -5F, 1, 16, 10);
        s6.setRotationPoint(0F, 16F, 0F);
        s6.setTextureSize(80, 32);
        s6.mirror = true;
        setRotation(s6, 0F, 0F, 0F);
        s7 = new ModelRenderer(this, 58, 0);
        s7.addBox(-5F, -8F, -8F, 10, 16, 1);
        s7.setRotationPoint(0F, 16F, 0F);
        s7.setTextureSize(80, 32);
        s7.mirror = true;
        setRotation(s7, 0F, 0F, 0F);
        s8 = new ModelRenderer(this, 58, 0);
        s8.addBox(-5F, -8F, 7F, 10, 16, 1);
        s8.setRotationPoint(0F, 16F, 0F);
        s8.setTextureSize(80, 32);
        s8.mirror = true;
        setRotation(s8, 0F, 0F, 0F);
        centralrod = new ModelRenderer(this, 28, 0);
        centralrod.addBox(-1F, -8F, -1F, 2, 16, 2);
        centralrod.setRotationPoint(0F, 16F, 0F);
        centralrod.setTextureSize(80, 32);
        centralrod.mirror = true;
        setRotation(centralrod, 0F, 0F, 0F);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        pilar1.render(f5);
        pilar2.render(f5);
        pilar3.render(f5);
        pilar4.render(f5);
        fuel1.render(f5);
        fuel2.render(f5);
        fuel3.render(f5);
        fuel4.render(f5);
        s5.render(f5);
        s6.render(f5);
        s7.render(f5);
        s8.render(f5);
        centralrod.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void renderStatic(float f5) {
        pilar1.render(f5);
        pilar2.render(f5);
        pilar3.render(f5);
        pilar4.render(f5);
        s5.render(f5);
        s6.render(f5);
        s7.render(f5);
        s8.render(f5);
        centralrod.render(f5);
    }

    public void renderDynamic(float f5, boolean[] a) {
        if (a == null) return;
        if (a[0]) fuel1.render(f5);
        if (a[1]) fuel2.render(f5);
        if (a[2]) fuel3.render(f5);
        if (a[3]) fuel4.render(f5);
    }

}
