// Date: 30/05/2015 23:27:03
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX


package com.cout970.magneticraft.client.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelOilDistillery extends ModelBase {
    //fields
    ModelRenderer Shape1;
    ModelRenderer Shape2;
    ModelRenderer Shape3;
    ModelRenderer Shape4;
    ModelRenderer Shape5;
    ModelRenderer Shape6;
    ModelRenderer Shape7;
    ModelRenderer Shape8;
    ModelRenderer Shape9;
    ModelRenderer Shape10;
    ModelRenderer Shape11;
    ModelRenderer Shape12;
    ModelRenderer Shape13;
    ModelRenderer Shape14;
    ModelRenderer Shape15;

    public ModelOilDistillery() {
        textureWidth = 256;
        textureHeight = 256;

        Shape1 = new ModelRenderer(this, 0, 0);
        Shape1.addBox(0F, 0F, 1F, 48, 16, 48);
        Shape1.setRotationPoint(-8F, 8F, -9F);
        Shape1.setTextureSize(256, 256);
        Shape1.mirror = true;
        setRotation(Shape1, 0F, 0F, 0F);
        Shape2 = new ModelRenderer(this, 0, 65);
        Shape2.addBox(0F, 0F, 0F, 48, 32, 16);
        Shape2.setRotationPoint(-8F, -24F, -8F);
        Shape2.setTextureSize(256, 256);
        Shape2.mirror = true;
        setRotation(Shape2, 0F, 0F, 0F);
        Shape3 = new ModelRenderer(this, 0, 114);
        Shape3.addBox(0F, 0F, 0F, 22, 30, 30);
        Shape3.setRotationPoint(-6F, -22F, 8F);
        Shape3.setTextureSize(256, 256);
        Shape3.mirror = true;
        setRotation(Shape3, 0F, 0F, 0F);
        Shape4 = new ModelRenderer(this, 128, 66);
        Shape4.addBox(0F, 0F, 0F, 1, 1, 31);
        Shape4.setRotationPoint(-7F, -18F, 8F);
        Shape4.setTextureSize(256, 256);
        Shape4.mirror = true;
        setRotation(Shape4, 0F, 0F, 0F);
        Shape5 = new ModelRenderer(this, 128, 66);
        Shape5.addBox(0F, 0F, 0F, 1, 1, 31);
        Shape5.setRotationPoint(-7F, -9F, 8F);
        Shape5.setTextureSize(256, 256);
        Shape5.mirror = true;
        setRotation(Shape5, 0F, 0F, 0F);
        Shape6 = new ModelRenderer(this, 128, 66);
        Shape6.addBox(0F, 0F, 0F, 1, 1, 31);
        Shape6.setRotationPoint(-7F, 0F, 8F);
        Shape6.setTextureSize(256, 256);
        Shape6.mirror = true;
        setRotation(Shape6, 0F, 0F, 0F);
        Shape7 = new ModelRenderer(this, 0, 114);
        Shape7.addBox(0F, 0F, 0F, 22, 30, 30);
        Shape7.setRotationPoint(16F, -22F, 8F);
        Shape7.setTextureSize(256, 256);
        Shape7.mirror = true;
        setRotation(Shape7, 0F, 0F, 0F);
        Shape8 = new ModelRenderer(this, 128, 66);
        Shape8.addBox(0F, 0F, 0F, 1, 1, 31);
        Shape8.setRotationPoint(38F, -18F, 8F);
        Shape8.setTextureSize(256, 256);
        Shape8.mirror = true;
        setRotation(Shape8, 0F, 0F, 0F);
        Shape9 = new ModelRenderer(this, 128, 66);
        Shape9.addBox(0F, 0F, 0F, 1, 1, 31);
        Shape9.setRotationPoint(38F, -9F, 8F);
        Shape9.setTextureSize(256, 256);
        Shape9.mirror = true;
        setRotation(Shape9, 0F, 0F, 0F);
        Shape10 = new ModelRenderer(this, 128, 66);
        Shape10.addBox(0F, 0F, 0F, 1, 1, 31);
        Shape10.setRotationPoint(38F, 0F, 8F);
        Shape10.setTextureSize(256, 256);
        Shape10.mirror = true;
        setRotation(Shape10, 0F, 0F, 0F);
        Shape11 = new ModelRenderer(this, 0, 175);
        Shape11.addBox(0F, 0F, 0F, 44, 1, 1);
        Shape11.setRotationPoint(-6F, -18F, 38F);
        Shape11.setTextureSize(256, 256);
        Shape11.mirror = true;
        setRotation(Shape11, 0F, 0F, 0F);
        Shape12 = new ModelRenderer(this, 0, 175);
        Shape12.addBox(0F, 0F, 0F, 44, 1, 1);
        Shape12.setRotationPoint(-6F, -9F, 38F);
        Shape12.setTextureSize(256, 256);
        Shape12.mirror = true;
        setRotation(Shape12, 0F, 0F, 0F);
        Shape13 = new ModelRenderer(this, 0, 175);
        Shape13.addBox(0F, 0F, 0F, 44, 1, 1);
        Shape13.setRotationPoint(-6F, 0F, 38F);
        Shape13.setTextureSize(256, 256);
        Shape13.mirror = true;
        setRotation(Shape13, 0F, 0F, 0F);
        Shape14 = new ModelRenderer(this, 21, 178);
        Shape14.addBox(0F, 0F, 0F, 8, 8, 2);
        Shape14.setRotationPoint(12F, -4F, 38F);
        Shape14.setTextureSize(256, 256);
        Shape14.mirror = true;
        setRotation(Shape14, 0F, 0F, 0F);
        Shape15 = new ModelRenderer(this, 15, 189);
        Shape15.addBox(0F, 0F, 0F, 8, 2, 8);
        Shape15.setRotationPoint(12F, -24F, 12F);
        Shape15.setTextureSize(256, 256);
        Shape15.mirror = true;
        setRotation(Shape15, 0F, 0F, 0F);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        super.render(entity, f, f1, f2, f3, f4, f5);
//    setRotationAngles(f, f1, f2, f3, f4, f5);
        Shape1.render(f5);
        Shape2.render(f5);
        Shape3.render(f5);
        Shape4.render(f5);
        Shape5.render(f5);
        Shape6.render(f5);
        Shape7.render(f5);
        Shape8.render(f5);
        Shape9.render(f5);
        Shape10.render(f5);
        Shape11.render(f5);
        Shape12.render(f5);
        Shape13.render(f5);
        Shape14.render(f5);
        Shape15.render(f5);
    }

    public void renderStatic(float f5) {
        Shape1.render(f5);
        Shape2.render(f5);
        Shape3.render(f5);
        Shape4.render(f5);
        Shape5.render(f5);
        Shape6.render(f5);
        Shape7.render(f5);
        Shape8.render(f5);
        Shape9.render(f5);
        Shape10.render(f5);
        Shape11.render(f5);
        Shape12.render(f5);
        Shape13.render(f5);
        Shape14.render(f5);
        Shape15.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }
}
