// Date: 02/11/2014 13:01:00
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX


package com.cout970.magneticraft.client.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelMirror extends ModelBase {
    //fields
    ModelRenderer base;
    ModelRenderer pole;
    ModelRenderer rotor;
    ModelRenderer mirror;

    public ModelMirror() {
        textureWidth = 56;
        textureHeight = 20;

        base = new ModelRenderer(this, 0, 15);
        base.addBox(-2F, 7F, -2F, 4, 1, 4);
        base.setRotationPoint(0F, 16F, 0F);
        base.setTextureSize(56, 20);
        base.mirror = true;
        setRotation(base, 0F, 0F, 0F);
        pole = new ModelRenderer(this, 0, 4);
        pole.addBox(-0.5F, 0F, -0.5F, 1, 7, 1);
        pole.setRotationPoint(0F, 16F, 0F);
        pole.setTextureSize(56, 20);
        pole.mirror = true;
        setRotation(pole, 0F, 0F, 0F);
        rotor = new ModelRenderer(this, 0, 0);
        rotor.addBox(-1F, -1F, -1F, 2, 2, 2);
        rotor.setRotationPoint(0F, 16F, 0F);
        rotor.setTextureSize(56, 20);
        rotor.mirror = true;
        setRotation(rotor, 0F, 0F, 0F);
        mirror = new ModelRenderer(this, 0, 0);
        mirror.addBox(-7F, -2F, -7F, 14, 1, 14);
        mirror.setRotationPoint(0F, 16F, 0F);
        mirror.setTextureSize(56, 20);
        mirror.mirror = true;
        setRotation(mirror, 0F, 0F, 0F);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5, entity);

        rotor.render(f5);
        mirror.render(f5);
    }

    public void renderStatic(float f5) {
        base.render(f5);
        pole.render(f5);
    }

    public void renderDynamic(float f5, double z) {
        rotor.rotateAngleZ = (float) z;
        mirror.rotateAngleZ = (float) z;
        rotor.render(f5);
        mirror.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity t) {
        super.setRotationAngles(f, f1, f2, f3, f4, f5, t);
    }

}
