// Date: 14/01/2015 4:44:57
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX


package com.cout970.magneticraft.client.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelWire extends ModelBase {
    //fields
    ModelRenderer center;
    ModelRenderer back;
    ModelRenderer left;
    ModelRenderer front;
    ModelRenderer right;
    ModelRenderer unconnected;

    public ModelWire() {
        textureWidth = 40;
        textureHeight = 32;

        center = new ModelRenderer(this, 0, 0);
        center.addBox(-2F, 5F, -2F, 4, 3, 4);
        center.setRotationPoint(0F, 16F, 0F);
        center.setTextureSize(40, 32);
        center.mirror = true;
        setRotation(center, 0F, 0F, 0F);
        back = new ModelRenderer(this, 0, 23);
        back.addBox(-2F, 5F, 2F, 4, 3, 6);
        back.setRotationPoint(0F, 16F, 0F);
        back.setTextureSize(40, 32);
        back.mirror = true;
        setRotation(back, 0F, 0F, 0F);
        left = new ModelRenderer(this, 20, 18);
        left.addBox(2F, 5F, -2F, 6, 3, 4);
        left.setRotationPoint(0F, 16F, 0F);
        left.setTextureSize(40, 32);
        left.mirror = true;
        setRotation(left, 0F, 0F, 0F);
        front = new ModelRenderer(this, 0, 14);
        front.addBox(-2F, 5F, -8F, 4, 3, 6);
        front.setRotationPoint(0F, 16F, 0F);
        front.setTextureSize(40, 32);
        front.mirror = true;
        setRotation(front, 0F, 0F, 0F);
        right = new ModelRenderer(this, 20, 25);
        right.addBox(-8F, 5F, -2F, 6, 3, 4);
        right.setRotationPoint(0F, 16F, 0F);
        right.setTextureSize(40, 32);
        right.mirror = true;
        setRotation(right, 0F, 0F, 0F);
        unconnected = new ModelRenderer(this, 0, 7);
        unconnected.addBox(-5F, 5F, -2F, 10, 3, 4);
        unconnected.setRotationPoint(0F, 16F, 0F);
        unconnected.setTextureSize(40, 32);
        unconnected.mirror = true;
        setRotation(unconnected, 0F, 0F, 0F);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        super.render(entity, f, f1, f2, f3, f4, f5);
        center.render(f5);
        back.render(f5);
        left.render(f5);
        front.render(f5);
        right.render(f5);
        unconnected.render(f5);
    }

    public void renderStatic(float f5) {
        center.render(f5);
    }

    public void renderDynamic(float f5, int conn) {
        if ((conn & 1) > 0) back.render(f5);
        if ((conn & 2) > 0) left.render(f5);
        if ((conn & 4) > 0) front.render(f5);
        if ((conn & 8) > 0) right.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

}
