// Date: 25/04/2015 15:54:56
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX


package com.cout970.magneticraft.client.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelElectricSword extends ModelBase {
    //fields
    ModelRenderer stick;
    ModelRenderer guard;

    public ModelElectricSword() {
        textureWidth = 16;
        textureHeight = 25;

        stick = new ModelRenderer(this, 0, 0);
        stick.addBox(0F, -24F, 0F, 1, 24, 1);
        stick.setRotationPoint(0F, 16F, 0F);
        stick.setTextureSize(16, 25);
        stick.mirror = true;
        setRotation(stick, 0F, 0F, 0F);
        guard = new ModelRenderer(this, 4, 0);
        guard.addBox(-1F, -5F, -1F, 3, 1, 3);
        guard.setRotationPoint(0F, 16F, 0F);
        guard.setTextureSize(16, 25);
        guard.mirror = true;
        setRotation(guard, 0F, 0F, 0F);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        super.render(entity, f, f1, f2, f3, f4, f5);
        //    setRotationAngles(f, f1, f2, f3, f4, f5);
        stick.render(f5);
        guard.render(f5);
    }

    public void renderStatic(float f5) {
        stick.render(f5);
        guard.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

}
