// Date: 10/01/2015 15:31:12
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX


package com.cout970.magneticraft.client.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelTransformer_MH extends ModelBase {
    //fields
    ModelRenderer base;
    ModelRenderer main;
    ModelRenderer in;
    ModelRenderer out;

    public ModelTransformer_MH() {
        textureWidth = 64;
        textureHeight = 64;

        base = new ModelRenderer(this, 0, 28);
        base.addBox(0F, 0F, 0F, 16, 1, 16);
        base.setRotationPoint(-8F, 23F, -8F);
        base.setTextureSize(64, 64);
        base.mirror = true;
        setRotation(base, 0F, 0F, 0F);
        main = new ModelRenderer(this, 0, 0);
        main.addBox(-6F, -7F, -7F, 12, 14, 14);
        main.setRotationPoint(0F, 16F, 0F);
        main.setTextureSize(64, 64);
        main.mirror = true;
        setRotation(main, 0F, 0F, 0F);
        in = new ModelRenderer(this, 0, 45);
        in.addBox(6F, -3F, -3F, 2, 6, 6);
        in.setRotationPoint(0F, 16F, 0F);
        in.setTextureSize(64, 64);
        in.mirror = true;
        setRotation(in, 0F, 0F, 0F);
        out = new ModelRenderer(this, 16, 45);
        out.addBox(-8F, -4F, -4F, 2, 8, 8);
        out.setRotationPoint(0F, 16F, 0F);
        out.setTextureSize(64, 64);
        out.mirror = true;
        setRotation(out, 0F, 0F, 0F);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        base.render(f5);
        main.render(f5);
        in.render(f5);
        out.render(f5);
    }

    public void renderStatic(float f5) {
        base.render(f5);
        main.render(f5);
        in.render(f5);
        out.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }
}
