// Date: 24/06/2015 0:48:53
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX


package com.cout970.magneticraft.client.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelAlternator extends ModelBase {
    //fields
    ModelRenderer Shape1;
    ModelRenderer Shape2;
    ModelRenderer Shape3;
    ModelRenderer Shape4;
    ModelRenderer Shape5;
    ModelRenderer Shape6;
    ModelRenderer Shape7;
    ModelRenderer Shape8;
    ModelRenderer Shape9;
    ModelRenderer Shape10;
    ModelRenderer Shape11;

    public ModelAlternator() {
        textureWidth = 110;
        textureHeight = 42;

        Shape1 = new ModelRenderer(this, 0, 17);
        Shape1.addBox(-5F, -5F, -7F, 10, 10, 14);
        Shape1.setRotationPoint(0F, 16F, 0F);
        Shape1.setTextureSize(110, 42);
        Shape1.mirror = true;
        setRotation(Shape1, 0F, 0F, 0F);
        Shape2 = new ModelRenderer(this, 64, 0);
        Shape2.addBox(-2F, -2F, -8F, 4, 4, 1);
        Shape2.setRotationPoint(0F, 16F, 0F);
        Shape2.setTextureSize(110, 42);
        Shape2.mirror = true;
        setRotation(Shape2, 0F, 0F, 0F);
        Shape3 = new ModelRenderer(this, 0, 0);
        Shape3.addBox(-8F, 7F, -8F, 16, 1, 16);
        Shape3.setRotationPoint(0F, 16F, 0F);
        Shape3.setTextureSize(110, 42);
        Shape3.mirror = true;
        setRotation(Shape3, 0F, 0F, 0F);
        Shape4 = new ModelRenderer(this, 64, 5);
        Shape4.addBox(-6F, -6F, 5F, 12, 1, 1);
        Shape4.setRotationPoint(0F, 16F, 0F);
        Shape4.setTextureSize(110, 42);
        Shape4.mirror = true;
        setRotation(Shape4, 0F, 0F, 0F);
        Shape5 = new ModelRenderer(this, 64, 7);
        Shape5.addBox(-6F, -6F, -6F, 12, 1, 1);
        Shape5.setRotationPoint(0F, 16F, 0F);
        Shape5.setTextureSize(110, 42);
        Shape5.mirror = true;
        setRotation(Shape5, 0F, 0F, 0F);
        Shape6 = new ModelRenderer(this, 90, 0);
        Shape6.addBox(-6F, -5F, -6F, 1, 10, 1);
        Shape6.setRotationPoint(0F, 16F, 0F);
        Shape6.setTextureSize(110, 42);
        Shape6.mirror = true;
        setRotation(Shape6, 0F, 0F, 0F);
        Shape7 = new ModelRenderer(this, 95, 0);
        Shape7.addBox(5F, -5F, -6F, 1, 10, 1);
        Shape7.setRotationPoint(0F, 16F, 0F);
        Shape7.setTextureSize(110, 42);
        Shape7.mirror = true;
        setRotation(Shape7, 0F, 0F, 0F);
        Shape8 = new ModelRenderer(this, 48, 18);
        Shape8.addBox(-6F, 5F, -8F, 12, 2, 16);
        Shape8.setRotationPoint(0F, 16F, 0F);
        Shape8.setTextureSize(110, 42);
        Shape8.mirror = true;
        setRotation(Shape8, 0F, 0F, 0F);
        Shape9 = new ModelRenderer(this, 64, 9);
        Shape9.addBox(-4F, -4F, 7F, 8, 8, 1);
        Shape9.setRotationPoint(0F, 16F, 0F);
        Shape9.setTextureSize(110, 42);
        Shape9.mirror = true;
        setRotation(Shape9, 0F, 0F, 0F);
        Shape10 = new ModelRenderer(this, 100, 0);
        Shape10.addBox(5F, -5F, 5F, 1, 10, 1);
        Shape10.setRotationPoint(0F, 16F, 0F);
        Shape10.setTextureSize(110, 42);
        Shape10.mirror = true;
        setRotation(Shape10, 0F, 0F, 0F);
        Shape11 = new ModelRenderer(this, 105, 0);
        Shape11.addBox(-6F, -5F, 5F, 1, 10, 1);
        Shape11.setRotationPoint(0F, 16F, 0F);
        Shape11.setTextureSize(110, 42);
        Shape11.mirror = true;
        setRotation(Shape11, 0F, 0F, 0F);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        super.render(entity, f, f1, f2, f3, f4, f5);
        Shape1.render(f5);
        Shape2.render(f5);
        Shape3.render(f5);
        Shape4.render(f5);
        Shape5.render(f5);
        Shape6.render(f5);
        Shape7.render(f5);
        Shape8.render(f5);
        Shape9.render(f5);
        Shape10.render(f5);
        Shape11.render(f5);
    }

    public void renderStatic(float f5) {
        Shape1.render(f5);
        Shape2.render(f5);
        Shape3.render(f5);
        Shape4.render(f5);
        Shape5.render(f5);
        Shape6.render(f5);
        Shape7.render(f5);
        Shape8.render(f5);
        Shape9.render(f5);
        Shape10.render(f5);
        Shape11.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }
}
