// Date: 02/11/2015 18:59:00
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package com.cout970.magneticraft.client.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelPumpjack extends ModelBase {
	// fields
	ModelRenderer Shape1;
	ModelRenderer Shape2;
	ModelRenderer Shape3;
	ModelRenderer Shape4;
	ModelRenderer Shape5;
	ModelRenderer Shape7;
	ModelRenderer Shape8;
	ModelRenderer Shape9;
	ModelRenderer Shape6;
	ModelRenderer Shape10;
	ModelRenderer Shape11;
	ModelRenderer Shape12;
	ModelRenderer Shape13;
	ModelRenderer Shape14;
	ModelRenderer Shape15;
	ModelRenderer Shape17;
	ModelRenderer Shape18;
	ModelRenderer Shape19;
	ModelRenderer Shape20;
	ModelRenderer Shape21;
	ModelRenderer Shape22;
	ModelRenderer Shape23;
	ModelRenderer Shape24;
	ModelRenderer Shape25;
	ModelRenderer Shape26;
	ModelRenderer Shape27;
	ModelRenderer Shape28;
	ModelRenderer Shape29;
	ModelRenderer Shape30;
	ModelRenderer Shape31;
	ModelRenderer Shape16;

	public ModelPumpjack() {
		textureWidth = 128;
		textureHeight = 128;

		Shape1 = new ModelRenderer(this, 64, 20);
		Shape1.addBox(-1F, -25F, 0F, 2, 26, 1);
		Shape1.setRotationPoint(0F, 16F, -8F);
		Shape1.setTextureSize(128, 128);
		Shape1.mirror = true;
		setRotation(Shape1, 0F, 0F, 0F);
		Shape2 = new ModelRenderer(this, 0, 90);
		Shape2.addBox(0F, -3F, -3F, 2, 6, 6);
		Shape2.setRotationPoint(-8F, 16F, 0F);
		Shape2.setTextureSize(128, 128);
		Shape2.mirror = true;
		setRotation(Shape2, 0F, 0F, 0F);
		Shape3 = new ModelRenderer(this, 0, 83);
		Shape3.addBox(0F, 5F, -2F, 2, 3, 4);
		Shape3.setRotationPoint(-8F, 16F, 0F);
		Shape3.setTextureSize(128, 128);
		Shape3.mirror = true;
		setRotation(Shape3, 0F, 0F, 0F);
		Shape4 = new ModelRenderer(this, 0, 57);
		Shape4.addBox(-4F, -3F, -6F, 12, 14, 12);
		Shape4.setRotationPoint(30F, 13F, 0F);
		Shape4.setTextureSize(128, 128);
		Shape4.mirror = true;
		setRotation(Shape4, 0F, 0F, 0F);
		Shape5 = new ModelRenderer(this, 0, 51);
		Shape5.addBox(-1.5F, -1F, -2F, 4, 2, 4);
		Shape5.setRotationPoint(32F, 9F, 0F);
		Shape5.setTextureSize(128, 128);
		Shape5.mirror = true;
		setRotation(Shape5, 0F, 0F, 0F);
		Shape7 = new ModelRenderer(this, 12, 83);
		Shape7.addBox(-1F, -0.5F, -2F, 2, 1, 4);
		Shape7.setRotationPoint(16F, -8F, 0F);
		Shape7.setTextureSize(128, 128);
		Shape7.mirror = true;
		setRotation(Shape7, 0F, 0F, 0F);
		Shape8 = new ModelRenderer(this, 16, 90);
		Shape8.addBox(-14F, -3F, -2F, 28, 3, 4);
		Shape8.setRotationPoint(16F, -8F, 0F);
		Shape8.setTextureSize(128, 128);
		Shape8.mirror = true;
		setRotation(Shape8, 0F, 0F, 0F);
		Shape9 = new ModelRenderer(this, 0, 32);
		Shape9.addBox(14F, -8F, -2.5F, 5, 14, 5);
		Shape9.setRotationPoint(16F, -8F, 0F);
		Shape9.setTextureSize(128, 128);
		Shape9.mirror = true;
		setRotation(Shape9, 0F, 0F, 0F);
		Shape6 = new ModelRenderer(this, 62, 112);
		Shape6.addBox(-7.5F, 0F, -7F, 2, 2, 14);
		Shape6.setRotationPoint(16F, 22F, 0F);
		Shape6.setTextureSize(128, 128);
		Shape6.mirror = true;
		setRotation(Shape6, 0F, 0F, 0F);
		Shape10 = new ModelRenderer(this, 48, 57);
		Shape10.addBox(5.5F, 0F, -7F, 2, 2, 14);
		Shape10.setRotationPoint(16F, 22F, 0F);
		Shape10.setTextureSize(128, 128);
		Shape10.mirror = true;
		setRotation(Shape10, 0F, 0F, 0F);
		Shape11 = new ModelRenderer(this, 20, 24);
		Shape11.addBox(-0.5F, 0F, 0.9F, 1, 32, 1);
		Shape11.setRotationPoint(16F, -8F, 0F);
		Shape11.setTextureSize(128, 128);
		Shape11.mirror = true;
		setRotation(Shape11, 0.1396263F, 0F, 0.2094395F);
		Shape12 = new ModelRenderer(this, 24, 24);
		Shape12.addBox(-0.5F, 0F, -1.9F, 1, 32, 1);
		Shape12.setRotationPoint(16F, -8F, 0F);
		Shape12.setTextureSize(128, 128);
		Shape12.mirror = true;
		setRotation(Shape12, -0.1396263F, 0F, 0.2094395F);
		Shape13 = new ModelRenderer(this, 28, 24);
		Shape13.addBox(-0.5F, 0F, 0.9F, 1, 32, 1);
		Shape13.setRotationPoint(16F, -8F, 0F);
		Shape13.setTextureSize(128, 128);
		Shape13.mirror = true;
		setRotation(Shape13, 0.1396263F, 0F, -0.2094395F);
		Shape14 = new ModelRenderer(this, 32, 24);
		Shape14.addBox(-0.5F, 0F, -1.9F, 1, 32, 1);
		Shape14.setRotationPoint(16F, -8F, 0F);
		Shape14.setTextureSize(128, 128);
		Shape14.mirror = true;
		setRotation(Shape14, -0.1396263F, 0F, -0.2094395F);
		Shape15 = new ModelRenderer(this, 12, 112);
		Shape15.addBox(-17F, -0.5F, -7F, 2, 2, 14);
		Shape15.setRotationPoint(16F, -8F, 0F);
		Shape15.setTextureSize(128, 128);
		Shape15.mirror = true;
		setRotation(Shape15, 0F, 0F, 0F);
		Shape17 = new ModelRenderer(this, 0, 0);
		Shape17.addBox(-9F, -5F, -4F, 11, 13, 8);
		Shape17.setRotationPoint(3F, 16F, 0F);
		Shape17.setTextureSize(128, 128);
		Shape17.mirror = true;
		setRotation(Shape17, 0F, 0F, 0F);
		Shape18 = new ModelRenderer(this, 36, 43);
		Shape18.addBox(-1F, -1F, -6F, 2, 2, 12);
		Shape18.setRotationPoint(0F, 16F, 0F);
		Shape18.setTextureSize(128, 128);
		Shape18.mirror = true;
		setRotation(Shape18, 0F, 0F, 0F);
		Shape19 = new ModelRenderer(this, 12, 102);
		Shape19.addBox(-1F, -1F, -7F, 2, 6, 1);
		Shape19.setRotationPoint(0F, 16F, 0F);
		Shape19.setTextureSize(128, 128);
		Shape19.mirror = true;
		setRotation(Shape19, 0F, 0F, 1.570796F);
		Shape20 = new ModelRenderer(this, 24, 83);
		Shape20.addBox(-3F, 5F, -7F, 6, 2, 2);
		Shape20.setRotationPoint(0F, 16F, 0F);
		Shape20.setTextureSize(128, 128);
		Shape20.mirror = true;
		setRotation(Shape20, 0F, 0F, 1.570796F);
		Shape21 = new ModelRenderer(this, 18, 102);
		Shape21.addBox(-1F, -1F, 6F, 2, 6, 1);
		Shape21.setRotationPoint(0F, 16F, 0F);
		Shape21.setTextureSize(128, 128);
		Shape21.mirror = true;
		setRotation(Shape21, 0F, 0F, 1.570796F);
		Shape22 = new ModelRenderer(this, 24, 102);
		Shape22.addBox(-3F, 5F, 5F, 6, 2, 2);
		Shape22.setRotationPoint(0F, 16F, 0F);
		Shape22.setTextureSize(128, 128);
		Shape22.mirror = true;
		setRotation(Shape22, 0F, 0F, 1.570796F);
		Shape23 = new ModelRenderer(this, 70, 20);
		Shape23.addBox(-1F, -25F, 0F, 2, 26, 1);
		Shape23.setRotationPoint(0F, 16F, 7F);
		Shape23.setTextureSize(128, 128);
		Shape23.mirror = true;
		setRotation(Shape23, 0F, 0F, 0F);
		Shape24 = new ModelRenderer(this, 38, 0);
		Shape24.addBox(0F, -4F, -4F, 2, 8, 8);
		Shape24.setRotationPoint(38F, 16F, 0F);
		Shape24.setTextureSize(128, 128);
		Shape24.mirror = true;
		setRotation(Shape24, 0F, 0F, 0F);
		Shape25 = new ModelRenderer(this, 60, 20);
		Shape25.addBox(-0.5F, -16.5F, -0.5F, 1, 17, 1);
		Shape25.setRotationPoint(32.5F, 8F, 0F);
		Shape25.setTextureSize(128, 128);
		Shape25.mirror = true;
		setRotation(Shape25, 0F, 0F, 0F);
		Shape26 = new ModelRenderer(this, 12, 110);
		Shape26.addBox(0F, 0F, -1F, 3, 1, 1);
		Shape26.setRotationPoint(23F, 23F, 5F);
		Shape26.setTextureSize(128, 128);
		Shape26.mirror = true;
		setRotation(Shape26, 0F, 0F, 0F);
		Shape27 = new ModelRenderer(this, 58, 0);
		Shape27.addBox(-4F, -4F, -8F, 8, 8, 2);
		Shape27.setRotationPoint(32F, 16F, 0F);
		Shape27.setTextureSize(128, 128);
		Shape27.mirror = true;
		setRotation(Shape27, 0F, 0F, 0F);
		Shape28 = new ModelRenderer(this, 24, 108);
		Shape28.addBox(0F, 0F, 0F, 11, 2, 2);
		Shape28.setRotationPoint(10.5F, 22F, 4F);
		Shape28.setTextureSize(128, 128);
		Shape28.mirror = true;
		setRotation(Shape28, 0F, 0F, 0F);
		Shape29 = new ModelRenderer(this, 50, 108);
		Shape29.addBox(0F, 0F, 0F, 11, 2, 2);
		Shape29.setRotationPoint(10.5F, 22F, -6F);
		Shape29.setTextureSize(128, 128);
		Shape29.mirror = true;
		setRotation(Shape29, 0F, 0F, 0F);
		Shape30 = new ModelRenderer(this, 22, 97);
		Shape30.addBox(0F, 0F, 0F, 4, 1, 1);
		Shape30.setRotationPoint(5F, 23F, 2F);
		Shape30.setTextureSize(128, 128);
		Shape30.mirror = true;
		setRotation(Shape30, 0F, 0F, 0F);
		Shape31 = new ModelRenderer(this, 58, 10);
		Shape31.addBox(-4F, -4F, 6F, 8, 8, 2);
		Shape31.setRotationPoint(32F, 16F, 0F);
		Shape31.setTextureSize(128, 128);
		Shape31.mirror = true;
		setRotation(Shape31, 0F, 0F, 0F);
		Shape16 = new ModelRenderer(this, 0, 21);
		Shape16.addBox(-17F, -1F, -1F, 3, 1, 2);
		Shape16.setRotationPoint(16F, -8F, 0F);
		Shape16.setTextureSize(128, 128);
		Shape16.mirror = true;
		setRotation(Shape16, 0F, 0F, 0F);
	}

	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
		super.render(entity, f, f1, f2, f3, f4, f5);
		Shape1.render(f5);
		Shape2.render(f5);
		Shape3.render(f5);
		Shape4.render(f5);
		Shape5.render(f5);
		Shape7.render(f5);
		Shape8.render(f5);
		Shape9.render(f5);
		Shape6.render(f5);
		Shape10.render(f5);
		Shape11.render(f5);
		Shape12.render(f5);
		Shape13.render(f5);
		Shape14.render(f5);
		Shape15.render(f5);
		Shape17.render(f5);
		Shape18.render(f5);
		Shape19.render(f5);
		Shape20.render(f5);
		Shape21.render(f5);
		Shape22.render(f5);
		Shape23.render(f5);
		Shape24.render(f5);
		Shape25.render(f5);
		Shape26.render(f5);
		Shape27.render(f5);
		Shape28.render(f5);
		Shape29.render(f5);
		Shape30.render(f5);
		Shape31.render(f5);
		Shape16.render(f5);
	}

	public void render(float f5, float anim, int mask) {
		
		float a = anim / 1000f;
		float rotation = (float) Math.toRadians(a * 360);
		float offsetXRotation = (float) -Math.sin(rotation) * 0.0625f * 4;
		float offsetYRotation = (float) Math.cos(rotation) * 0.0625f * 4;
		float headRotation = -offsetYRotation;
		//seems easy when is done
		float hardRotation = (float) (Math.acos(offsetXRotation / 1.5f) + Math.toRadians(-90));

		// hard part
		Shape1.rotateAngleZ = hardRotation;
		Shape23.rotateAngleZ = hardRotation;

		Shape1.offsetX = offsetXRotation;
		Shape1.offsetY = offsetYRotation;

		Shape23.offsetX = offsetXRotation;
		Shape23.offsetY = offsetYRotation;

		Shape1.render(f5);
		Shape23.render(f5);

		// head rotation
		Shape15.offsetX = (float) (Math.cos(headRotation) - 1);

		Shape8.rotateAngleZ = headRotation;
		Shape15.rotateAngleZ = headRotation;
		Shape16.rotateAngleZ = headRotation;
		Shape9.rotateAngleZ = headRotation;

		Shape8.render(f5);
		Shape15.render(f5);
		Shape16.render(f5);
		Shape9.render(f5);

		// engine rotation
		Shape18.rotateAngleZ = rotation;
		Shape19.rotateAngleZ = rotation;
		Shape20.rotateAngleZ = rotation;
		Shape21.rotateAngleZ = rotation;
		Shape22.rotateAngleZ = rotation;

		Shape18.render(f5);
		Shape19.render(f5);
		Shape20.render(f5);
		Shape21.render(f5);
		Shape22.render(f5);
		
		//another rotation
		Shape25.rotateAngleZ = -headRotation*0.0625f*2;
		Shape25.render(f5);

		// static render
		Shape4.render(f5);
		Shape5.render(f5);
		Shape7.render(f5);
		Shape6.render(f5);
		Shape10.render(f5);
		Shape11.render(f5);
		Shape12.render(f5);
		Shape13.render(f5);
		Shape14.render(f5);
		Shape17.render(f5);
		Shape26.render(f5);
		Shape28.render(f5);
		Shape29.render(f5);
		Shape30.render(f5);

		// connections
		if ((mask & 0x1) != 0)
			Shape27.render(f5);
		if ((mask & 0x2) != 0)
			Shape24.render(f5);
		if ((mask & 0x4) != 0)
			Shape31.render(f5);
		if ((mask & 0x8) != 0)
			Shape2.render(f5);
		if ((mask & 0x10) != 0)
			Shape3.render(f5);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}
}
