// Date: 28/09/2014 12:51:11
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX


package com.cout970.magneticraft.client.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;

public class ModelCableHigh extends ModelBase {
    //fields
    ModelRenderer base;
    ModelRenderer B;
    ModelRenderer F;
    ModelRenderer R;
    ModelRenderer L;
    ModelRenderer D;
    ModelRenderer U;

    public ModelCableHigh() {
        textureWidth = 64;
        textureHeight = 64;

        base = new ModelRenderer(this, 0, 0);
        base.addBox(-4F, -4F, -4F, 8, 8, 8);
        base.setRotationPoint(0F, 16F, 0F);
        base.setTextureSize(64, 64);
        base.mirror = true;
        setRotation(base, 0F, 0F, 0F);
        B = new ModelRenderer(this, 0, 52);
        B.addBox(-4F, -4F, 0F, 8, 8, 4);
        B.setRotationPoint(0F, 16F, 4F);
        B.setTextureSize(64, 64);
        B.mirror = true;
        setRotation(B, 0F, 0F, 0F);
        F = new ModelRenderer(this, 0, 40);
        F.addBox(-4F, -4F, -8F, 8, 8, 4);
        F.setRotationPoint(0F, 16F, 0F);
        F.setTextureSize(64, 64);
        F.mirror = true;
        setRotation(F, 0F, 0F, 0F);
        R = new ModelRenderer(this, 0, 24);
        R.addBox(-2F, -4F, -4F, 4, 8, 8);
        R.setRotationPoint(-6F, 16F, 0F);
        R.setTextureSize(64, 64);
        R.mirror = true;
        setRotation(R, 0F, 0F, 0F);
        L = new ModelRenderer(this, 24, 48);
        L.addBox(0F, -4F, -4F, 4, 8, 8);
        L.setRotationPoint(4F, 16F, 0F);
        L.setTextureSize(64, 64);
        L.mirror = true;
        setRotation(L, 0F, 0F, 0F);
        D = new ModelRenderer(this, 24, 36);
        D.addBox(-4F, 4F, -4F, 8, 4, 8);
        D.setRotationPoint(0F, 16F, 0F);
        D.setTextureSize(64, 64);
        D.mirror = true;
        setRotation(D, 0F, 0F, 0F);
        U = new ModelRenderer(this, 24, 24);
        U.addBox(-4F, -8F, -4F, 8, 4, 8);
        U.setRotationPoint(0F, 16F, 0F);
        U.setTextureSize(64, 64);
        U.mirror = true;
        setRotation(U, 0F, 0F, 0F);
    }

    public void render(float f5, boolean[] s) {
        if (s == null) return;

        if (s[0]) U.render(f5);
        if (s[1]) D.render(f5);
        if (s[2]) F.render(f5);
        if (s[3]) B.render(f5);
        if (s[4]) R.render(f5);
        if (s[5]) L.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void renderBase(float f5) {
        base.render(f5);
    }
}
