// Date: 21/12/2014 18:47:56
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX


package com.cout970.magneticraft.client.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelDrill extends ModelBase {
    //fields
    ModelRenderer pipe;
    ModelRenderer drill1;
    ModelRenderer drill2;
    ModelRenderer drill3;
    ModelRenderer drill4;
    ModelRenderer drill5;

    public ModelDrill() {
        textureWidth = 64;
        textureHeight = 32;

        pipe = new ModelRenderer(this, 40, 0);
        pipe.addBox(-2F, 0F, -2F, 4, 16, 4);
        pipe.setRotationPoint(0F, 8F, 0F);
        pipe.setTextureSize(64, 32);
        pipe.mirror = true;
        setRotation(pipe, 0F, 0F, 0F);
        drill1 = new ModelRenderer(this, 0, 0);
        drill1.addBox(-5F, 0F, -5F, 10, 1, 10);
        drill1.setRotationPoint(0F, 7F, 0F);
        drill1.setTextureSize(64, 32);
        drill1.mirror = true;
        setRotation(drill1, 0F, 0F, 0F);
        drill2 = new ModelRenderer(this, 0, 11);
        drill2.addBox(-4F, 0F, -4F, 8, 1, 8);
        drill2.setRotationPoint(0F, 6F, 0F);
        drill2.setTextureSize(64, 32);
        drill2.mirror = true;
        setRotation(drill2, 0F, 0F, 0F);
        drill3 = new ModelRenderer(this, 0, 20);
        drill3.addBox(-3F, 0F, -3F, 6, 1, 6);
        drill3.setRotationPoint(0F, 5F, 0F);
        drill3.setTextureSize(64, 32);
        drill3.mirror = true;
        setRotation(drill3, 0F, 0F, 0F);
        drill4 = new ModelRenderer(this, 0, 27);
        drill4.addBox(-2F, 0F, -2F, 4, 1, 4);
        drill4.setRotationPoint(0F, 4F, 0F);
        drill4.setTextureSize(64, 32);
        drill4.mirror = true;
        setRotation(drill4, 0F, 0F, 0F);
        drill5 = new ModelRenderer(this, 16, 27);
        drill5.addBox(-1F, 0F, -1F, 2, 1, 2);
        drill5.setRotationPoint(0F, 3F, 0F);
        drill5.setTextureSize(64, 32);
        drill5.mirror = true;
        setRotation(drill5, 0F, 0F, 0F);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        pipe.render(f5);
        drill1.render(f5);
        drill2.render(f5);
        drill3.render(f5);
        drill4.render(f5);
        drill5.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

}
