// Date: 10/02/2015 20:23:51
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX


package com.cout970.magneticraft.client.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelHeatCable extends ModelBase {
    //fields
    ModelRenderer base;
    ModelRenderer bottom;
    ModelRenderer top;
    ModelRenderer back;
    ModelRenderer front;
    ModelRenderer left;
    ModelRenderer right;

    public ModelHeatCable() {
        textureWidth = 64;
        textureHeight = 64;

        base = new ModelRenderer(this, 0, 0);
        base.addBox(-6F, -6F, -6F, 12, 12, 12);
        base.setRotationPoint(0F, 16F, 0F);
        base.setTextureSize(64, 64);
        base.mirror = true;
        setRotation(base, 0F, 0F, 0F);
        bottom = new ModelRenderer(this, 0, 48);
        bottom.addBox(-6F, 6F, -6F, 12, 2, 12);
        bottom.setRotationPoint(0F, 16F, 0F);
        bottom.setTextureSize(64, 64);
        bottom.mirror = true;
        setRotation(bottom, 0F, 0F, 0F);
        top = new ModelRenderer(this, 0, 48);
        top.addBox(-6F, -8F, -6F, 12, 2, 12);
        top.setRotationPoint(0F, 16F, 0F);
        top.setTextureSize(64, 64);
        top.mirror = true;
        setRotation(top, 0F, 0F, 0F);
        back = new ModelRenderer(this, 0, 24);
        back.addBox(-6F, -6F, 6F, 12, 12, 2);
        back.setRotationPoint(0F, 16F, 0F);
        back.setTextureSize(64, 64);
        back.mirror = true;
        setRotation(back, 0F, 0F, 0F);
        front = new ModelRenderer(this, 0, 24);
        front.addBox(-6F, -6F, -8F, 12, 12, 2);
        front.setRotationPoint(0F, 16F, 0F);
        front.setTextureSize(64, 64);
        front.mirror = true;
        setRotation(front, 0F, 0F, 0F);
        left = new ModelRenderer(this, 28, 24);
        left.addBox(6F, -6F, -6F, 2, 12, 12);
        left.setRotationPoint(0F, 16F, 0F);
        left.setTextureSize(64, 64);
        left.mirror = true;
        setRotation(left, 0F, 0F, 0F);
        right = new ModelRenderer(this, 28, 24);
        right.addBox(-8F, -6F, -6F, 2, 12, 12);
        right.setRotationPoint(0F, 16F, 0F);
        right.setTextureSize(64, 64);
        right.mirror = true;
        setRotation(right, 0F, 0F, 0F);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        super.render(entity, f, f1, f2, f3, f4, f5);
        base.render(f5);
        bottom.render(f5);
        top.render(f5);
        back.render(f5);
        front.render(f5);
        left.render(f5);
        right.render(f5);
    }

    public void renderStatic(float f5) {
        base.render(f5);
    }

    public void renderDynamic(float f5, byte con) {
        if ((con & (1)) > 0) bottom.render(f5);
        if ((con & (1 << 1)) > 0) top.render(f5);
        if ((con & (1 << 3)) > 0) back.render(f5);
        if ((con & (1 << 2)) > 0) front.render(f5);
        if ((con & (1 << 4)) > 0) left.render(f5);
        if ((con & (1 << 5)) > 0) right.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }
}
