// Date: 05/12/2015 0:19:30
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX


package com.cout970.magneticraft.client.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelKineticGenerator extends ModelBase {
    //fields
    ModelRenderer Shape1;
    ModelRenderer Shape2;
    ModelRenderer Shape3;
    ModelRenderer Shape4;
    ModelRenderer Shape5;
    ModelRenderer Shape6;
    ModelRenderer Shape7;
    ModelRenderer Shape8;
    ModelRenderer Shape9;
    ModelRenderer Shape10;
    ModelRenderer Shape11;

    public ModelKineticGenerator() {
        textureWidth = 64;
        textureHeight = 32;

        Shape1 = new ModelRenderer(this, 40, 0);
        Shape1.addBox(-2F, -8F, -8F, 4, 2, 2);
        Shape1.setRotationPoint(0F, 16F, 0F);
        Shape1.setTextureSize(64, 32);
        Shape1.mirror = true;
        setRotation(Shape1, 0F, 0F, 0F);
        Shape2 = new ModelRenderer(this, 40, 0);
        Shape2.addBox(-2F, 6F, -8F, 4, 2, 2);
        Shape2.setRotationPoint(0F, 16F, 0F);
        Shape2.setTextureSize(64, 32);
        Shape2.mirror = true;
        setRotation(Shape2, 0F, 0F, 0F);
        Shape3 = new ModelRenderer(this, 40, 0);
        Shape3.addBox(-2F, 6F, 6F, 4, 2, 2);
        Shape3.setRotationPoint(0F, 16F, 0F);
        Shape3.setTextureSize(64, 32);
        Shape3.mirror = true;
        setRotation(Shape3, 0F, 0F, 0F);
        Shape4 = new ModelRenderer(this, 40, 0);
        Shape4.addBox(-2F, -8F, 6F, 4, 2, 2);
        Shape4.setRotationPoint(0F, 16F, 0F);
        Shape4.setTextureSize(64, 32);
        Shape4.mirror = true;
        setRotation(Shape4, 0F, 0F, 0F);
        Shape5 = new ModelRenderer(this, 0, 0);
        Shape5.addBox(2F, -8F, -8F, 4, 16, 16);
        Shape5.setRotationPoint(0F, 16F, 0F);
        Shape5.setTextureSize(64, 32);
        Shape5.mirror = true;
        setRotation(Shape5, 0F, 0F, 0F);
        Shape6 = new ModelRenderer(this, 0, 0);
        Shape6.addBox(-6F, -8F, -8F, 4, 16, 16);
        Shape6.setRotationPoint(0F, 16F, 0F);
        Shape6.setTextureSize(64, 32);
        Shape6.mirror = true;
        setRotation(Shape6, 0F, 0F, 0F);
        Shape7 = new ModelRenderer(this, 40, 4);
        Shape7.addBox(-1.5F, -7F, -1F, 3, 14, 2);
        Shape7.setRotationPoint(0F, 16F, 0F);
        Shape7.setTextureSize(64, 32);
        Shape7.mirror = true;
        setRotation(Shape7, 0F, 0F, 0F);
        Shape8 = new ModelRenderer(this, 44, 16);
        Shape8.addBox(6F, -4F, -4F, 2, 8, 8);
        Shape8.setRotationPoint(0F, 16F, 0F);
        Shape8.setTextureSize(64, 32);
        Shape8.mirror = true;
        setRotation(Shape8, 0F, 0F, 0F);
        Shape9 = new ModelRenderer(this, 24, 0);
        Shape9.addBox(-8F, 4F, -3F, 2, 4, 6);
        Shape9.setRotationPoint(0F, 16F, 0F);
        Shape9.setTextureSize(64, 32);
        Shape9.mirror = true;
        setRotation(Shape9, 0F, 0F, 0F);
        Shape10 = new ModelRenderer(this, 0, 0);
        Shape10.addBox(-8F, -3F, -3F, 2, 6, 6);
        Shape10.setRotationPoint(0F, 16F, 0F);
        Shape10.setTextureSize(64, 32);
        Shape10.mirror = true;
        setRotation(Shape10, 0F, 0F, 0F);
        Shape11 = new ModelRenderer(this, 0, 12);
        Shape11.addBox(-2F, -1F, -1F, 4, 2, 2);
        Shape11.setRotationPoint(0F, 16F, 0F);
        Shape11.setTextureSize(64, 32);
        Shape11.mirror = true;
        setRotation(Shape11, 0F, 0F, 0F);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        super.render(entity, f, f1, f2, f3, f4, f5);
        Shape1.render(f5);
        Shape2.render(f5);
        Shape3.render(f5);
        Shape4.render(f5);
        Shape5.render(f5);
        Shape6.render(f5);
        Shape7.render(f5);
        Shape8.render(f5);
        Shape9.render(f5);
        Shape10.render(f5);
        Shape11.render(f5);
    }


    public void renderStatic(float f5) {
        Shape1.render(f5);
        Shape2.render(f5);
        Shape3.render(f5);
        Shape4.render(f5);
        Shape5.render(f5);
        Shape6.render(f5);

        Shape8.render(f5);
//        Shape9.render(f5);
        Shape10.render(f5);
        Shape11.render(f5);
    }

    public void renderDynamic(float f5, float g) {
        for (int i = 0; i < 6; i++) {
            Shape7.rotateAngleX = (float) Math.toRadians(i*360/12f+g);
            Shape7.render(f5);
        }
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

}
