// Date: 12/01/2015 14:16:17
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX


package com.cout970.magneticraft.client.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelTeslaCoil extends ModelBase {
    //fields
    ModelRenderer pilar;
    ModelRenderer base1;
    ModelRenderer base2;
    ModelRenderer coil;

    public ModelTeslaCoil() {
        textureWidth = 80;
        textureHeight = 86;

        pilar = new ModelRenderer(this, 48, 0);
        pilar.addBox(-4F, -21F, -4F, 8, 42, 8);
        pilar.setRotationPoint(0F, 0F, 0F);
        pilar.setTextureSize(80, 86);
        pilar.mirror = true;
        setRotation(pilar, 0F, 0F, 0F);
        base1 = new ModelRenderer(this, 0, 50);
        base1.addBox(-8F, 5F, -8F, 16, 3, 16);
        base1.setRotationPoint(0F, 16F, 0F);
        base1.setTextureSize(80, 86);
        base1.mirror = true;
        setRotation(base1, 0F, 0F, 0F);
        base2 = new ModelRenderer(this, 0, 69);
        base2.addBox(-7F, -40F, -7F, 14, 3, 14);
        base2.setRotationPoint(0F, 16F, 0F);
        base2.setTextureSize(80, 86);
        base2.mirror = true;
        setRotation(base2, 0F, 0F, 0F);
        coil = new ModelRenderer(this, 0, 0);
        coil.addBox(-6F, -19F, -6F, 12, 38, 12);
        coil.setRotationPoint(0F, 0F, 0F);
        coil.setTextureSize(80, 86);
        coil.mirror = true;
        setRotation(coil, 0F, 0F, 0F);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        pilar.render(f5);
        base1.render(f5);
        base2.render(f5);
        coil.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void renderStatic(float f5) {
        pilar.render(f5);
        base1.render(f5);
        base2.render(f5);
        coil.render(f5);
    }
}
