// Date: 12/04/2015 0:21:22
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX


package com.cout970.magneticraft.client.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelHeatSink extends ModelBase {
    //fields
    ModelRenderer base;
    ModelRenderer vent1;
    ModelRenderer vent2;
    ModelRenderer vent3;
    ModelRenderer vent4;
    ModelRenderer vent5;
    ModelRenderer vent6;

    public ModelHeatSink() {
        textureWidth = 64;
        textureHeight = 32;

        base = new ModelRenderer(this, 0, 15);
        base.addBox(-6F, 7F, -6F, 12, 1, 12);
        base.setRotationPoint(0F, 16F, 0F);
        base.setTextureSize(64, 32);
        base.mirror = true;
        setRotation(base, 0F, 0F, 0F);
        vent1 = new ModelRenderer(this, 0, 0);
        vent1.addBox(5F, 4F, -6F, 1, 3, 12);
        vent1.setRotationPoint(0F, 16F, 0F);
        vent1.setTextureSize(64, 32);
        vent1.mirror = true;
        setRotation(vent1, 0F, 0F, 0F);
        vent2 = new ModelRenderer(this, 0, 0);
        vent2.addBox(3F, 4F, -6F, 1, 3, 12);
        vent2.setRotationPoint(0F, 16F, 0F);
        vent2.setTextureSize(64, 32);
        vent2.mirror = true;
        setRotation(vent2, 0F, 0F, 0F);
        vent3 = new ModelRenderer(this, 0, 0);
        vent3.addBox(1F, 4F, -6F, 1, 3, 12);
        vent3.setRotationPoint(0F, 16F, 0F);
        vent3.setTextureSize(64, 32);
        vent3.mirror = true;
        setRotation(vent3, 0F, 0F, 0F);
        vent4 = new ModelRenderer(this, 0, 0);
        vent4.addBox(-6F, 4F, -6F, 1, 3, 12);
        vent4.setRotationPoint(0F, 16F, 0F);
        vent4.setTextureSize(64, 32);
        vent4.mirror = true;
        setRotation(vent4, 0F, 0F, 0F);
        vent5 = new ModelRenderer(this, 0, 0);
        vent5.addBox(-4F, 4F, -6F, 1, 3, 12);
        vent5.setRotationPoint(0F, 16F, 0F);
        vent5.setTextureSize(64, 32);
        vent5.mirror = true;
        setRotation(vent5, 0F, 0F, 0F);
        vent6 = new ModelRenderer(this, 0, 0);
        vent6.addBox(-2F, 4F, -6F, 1, 3, 12);
        vent6.setRotationPoint(0F, 16F, 0F);
        vent6.setTextureSize(64, 32);
        vent6.mirror = true;
        setRotation(vent6, 0F, 0F, 0F);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        super.render(entity, f, f1, f2, f3, f4, f5);
        base.render(f5);
        vent1.render(f5);
        vent2.render(f5);
        vent3.render(f5);
        vent4.render(f5);
        vent5.render(f5);
        vent6.render(f5);
    }

    public void renderStatic(float f5) {
        base.render(f5);
        vent1.render(f5);
        vent2.render(f5);
        vent3.render(f5);
        vent4.render(f5);
        vent5.render(f5);
        vent6.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

}
