// Date: 03/11/2014 22:58:39
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.cout970.magneticraft.client.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

import org.lwjgl.opengl.GL11;

public class ModelWindMillSmall extends ModelBase
{
  //fields
    ModelRenderer axix;
    ModelRenderer pole;
    ModelRenderer wool;
  
  public ModelWindMillSmall()
  {
    textureWidth = 48;
    textureHeight = 42;
    
      axix = new ModelRenderer(this, 0, 0);
      axix.addBox(-2F, -2F, -2F, 4, 10, 4);
      axix.setRotationPoint(0F, 16F, 0F);
      axix.setTextureSize(48, 42);
      axix.mirror = true;
      setRotation(axix, 0F, 0F, 0F);
      pole = new ModelRenderer(this, 0, 0);
      pole.addBox(-1F, 0F, 2F, 2, 2, 22);
      pole.setRotationPoint(0F, 16F, 0F);
      pole.setTextureSize(48, 42);
      pole.mirror = true;
      setRotation(pole, 0F, 0F, 0F);
      wool = new ModelRenderer(this, 0, 24);
      wool.addBox(0F, 0.5F, 7F, 7, 1, 16);
      wool.setRotationPoint(0F, 16F, 0F);
      wool.setTextureSize(48, 42);
      wool.mirror = true;
      setRotation(wool, 0F, 0F, 0.2617994F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5,entity);
    axix.render(f5);
    pole.render(f5);
    wool.render(f5);
  }

  public void renderStatic(float f5){
	  axix.render(f5);
	  GL11.glPushMatrix();
	  pole.render(f5);
	  wool.render(f5);
	  GL11.glRotatef(90, 0, 1, 0);
	  pole.render(f5);
	  wool.render(f5);
	  GL11.glRotatef(90, 0, 1, 0);
	  pole.render(f5);
	  wool.render(f5);
	  GL11.glRotatef(90, 0, 1, 0);
	  pole.render(f5);
	  wool.render(f5);
	  GL11.glPopMatrix();
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity t)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5,t);
  }

}
