// Date: 14/11/2014 17:01:02
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.cout970.magneticraft.client.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelShaft extends ModelBase
{
  //fields
    ModelRenderer Shaft;
    ModelRenderer Shape1;
    ModelRenderer Shape2;
    ModelRenderer Shape3;
    ModelRenderer Shape4;
    ModelRenderer Shape5;
    ModelRenderer Shape6;
    ModelRenderer Shape7;
    ModelRenderer Shape8;
  
  public ModelShaft()
  {
    textureWidth = 128;
    textureHeight = 64;
    
      Shaft = new ModelRenderer(this, 34, 46);
      Shaft.addBox(-2F, -2F, -7F, 4, 4, 7);
      Shaft.setRotationPoint(0F, 16F, 0F);
      Shaft.setTextureSize(128, 64);
      Shaft.mirror = true;
      setRotation(Shaft, 0F, 0F, 0F);
      Shape1 = new ModelRenderer(this, 30, 29);
      Shape1.addBox(-8F, -8F, -8F, 16, 16, 1);
      Shape1.setRotationPoint(0F, 16F, 0F);
      Shape1.setTextureSize(128, 64);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
      Shape2 = new ModelRenderer(this, 0, 32);
      Shape2.addBox(7F, -8F, -7F, 1, 1, 14);
      Shape2.setRotationPoint(0F, 16F, 0F);
      Shape2.setTextureSize(128, 64);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, 0F, 0F);
      Shape3 = new ModelRenderer(this, 0, 47);
      Shape3.addBox(-8F, -8F, 7F, 16, 16, 1);
      Shape3.setRotationPoint(0F, 16F, 0F);
      Shape3.setTextureSize(128, 64);
      Shape3.mirror = true;
      setRotation(Shape3, 0F, 0F, 0F);
      Shape4 = new ModelRenderer(this, 0, 15);
      Shape4.addBox(-8F, -8F, -7F, 1, 1, 14);
      Shape4.setRotationPoint(0F, 16F, 0F);
      Shape4.setTextureSize(128, 64);
      Shape4.mirror = true;
      setRotation(Shape4, 0F, 0F, 0F);
      Shape5 = new ModelRenderer(this, 0, 0);
      Shape5.addBox(-8F, 7F, -7F, 16, 1, 14);
      Shape5.setRotationPoint(0F, 16F, 0F);
      Shape5.setTextureSize(128, 64);
      Shape5.mirror = true;
      setRotation(Shape5, 0F, 0F, 0F);
      Shape6 = new ModelRenderer(this, 61, 0);
      Shape6.addBox(-8F, -8F, 0F, 16, 15, 1);
      Shape6.setRotationPoint(0F, 16F, 0F);
      Shape6.setTextureSize(128, 64);
      Shape6.mirror = true;
      setRotation(Shape6, 0F, 0F, 0F);
      Shape7 = new ModelRenderer(this, 30, 15);
      Shape7.addBox(-1F, -1F, 0F, 2, 2, 6);
      Shape7.setRotationPoint(0F, 16F, 1F);
      Shape7.setTextureSize(128, 64);
      Shape7.mirror = true;
      setRotation(Shape7, 0F, 0F, 0F);
      Shape8 = new ModelRenderer(this, 46, 15);
      Shape8.addBox(-0.5F, -0.5F, -2F, 1, 1, 5);
      Shape8.setRotationPoint(5F, 19F, 0F);
      Shape8.setTextureSize(128, 64);
      Shape8.mirror = true;
      setRotation(Shape8, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Shaft.render(f5);
    Shape1.render(f5);
    Shape2.render(f5);
    Shape3.render(f5);
    Shape4.render(f5);
    Shape5.render(f5);
    Shape6.render(f5);
    Shape7.render(f5);
    Shape8.render(f5);
  }
  
  public void renderStatic(float f5){
	    Shape1.render(f5);
	    Shape2.render(f5);
	    Shape3.render(f5);
	    Shape4.render(f5);
	    Shape5.render(f5);
	    Shape6.render(f5);
	    
	    
  }
  
  public void renderDynamic(float f5,int part,float rot){
	  if(part == 0){
		  Shaft.rotateAngleZ  = rot;
		  Shaft.render(f5);
	  }
	  if(part == 1){
		  Shape8.rotateAngleZ = rot;
		  Shape8.render(f5);
	  }
	  if(part == 2){
		  Shape7.rotateAngleZ = rot;
		  Shape7.render(f5);
	  }
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
}
