// Date: 03/11/2014 22:42:52
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.cout970.magneticraft.client.model;


import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelRotor extends ModelBase
{
  //fields
    ModelRenderer Shaft;
    ModelRenderer Shape1;
    ModelRenderer Shape2;
    ModelRenderer Shape3;
    ModelRenderer Shape4;
    ModelRenderer Shape5;
  
  public ModelRotor()
  {
    textureWidth = 128;
    textureHeight = 64;
    
      Shaft = new ModelRenderer(this, 34, 46);
      Shaft.addBox(-2F, -2F, -7F, 4, 4, 14);
      Shaft.setRotationPoint(0F, 16F, 0F);
      Shaft.setTextureSize(128, 64);
      Shaft.mirror = true;
      setRotation(Shaft, 0F, 0F, 0F);
      Shape1 = new ModelRenderer(this, 30, 29);
      Shape1.addBox(-8F, -8F, -8F, 16, 16, 1);
      Shape1.setRotationPoint(0F, 16F, 0F);
      Shape1.setTextureSize(128, 64);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
      Shape2 = new ModelRenderer(this, 0, 32);
      Shape2.addBox(7F, -8F, -7F, 1, 1, 14);
      Shape2.setRotationPoint(0F, 16F, 0F);
      Shape2.setTextureSize(128, 64);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, 0F, 0F);
      Shape3 = new ModelRenderer(this, 0, 47);
      Shape3.addBox(-8F, -8F, 7F, 16, 16, 1);
      Shape3.setRotationPoint(0F, 16F, 0F);
      Shape3.setTextureSize(128, 64);
      Shape3.mirror = true;
      setRotation(Shape3, 0F, 0F, 0F);
      Shape4 = new ModelRenderer(this, 0, 15);
      Shape4.addBox(-8F, -8F, -7F, 1, 1, 14);
      Shape4.setRotationPoint(0F, 16F, 0F);
      Shape4.setTextureSize(128, 64);
      Shape4.mirror = true;
      setRotation(Shape4, 0F, 0F, 0F);
      Shape5 = new ModelRenderer(this, 0, 0);
      Shape5.addBox(-8F, 7F, -7F, 16, 1, 14);
      Shape5.setRotationPoint(0F, 16F, 0F);
      Shape5.setTextureSize(128, 64);
      Shape5.mirror = true;
      setRotation(Shape5, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Shaft.render(f5);
    Shape1.render(f5);
    Shape2.render(f5);
    Shape3.render(f5);
    Shape4.render(f5);
    Shape5.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity t)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5,t);
  }

  public void renderStatic(float f5) {
	  Shape1.render(f5);
	  Shape2.render(f5);
	  Shape3.render(f5);
	  Shape4.render(f5);
	  Shape5.render(f5);
  }
  
  public void renderDynamic(float f5){
	  Shaft.render(f5);
  }

}
